var tableauQuestion = [
    {   question : "If you are driving at 80 mph, and you approach a residential area, it means that",
        propositionA : "You will need to speed up ahead",
        propositionB : "You can speed through as long as there are no other cars",
        propositionC : "You will have to slow down up ahead",
        propositionD : "You can maintain your speed",
        reponse : "C"},
        
    {   question : "While turning left on a green light, you see that a pedestrian is in the crosswalk. Who has the right of way?",
        propositionA : "The pedastrian, because they can cross the road with any light",
        propositionB : "Your vehicle because the light is green",
        propositionC : "The pedastrian, because s/he is crossing with the green light",
        propositionD : "Your vehicle, because vehicles are always given right-of-way",
        reponse : "C"},
        
    {   question : "Unless posted, the maximum speed in a residential area is ____ mph.",
        propositionA : "25",
        propositionB : "35",
        propositionC : "50",
        propositionD : "15",
        reponse : "A"},
    
    {   question : "Before every lane change, you should.",
        propositionA : "Check your mirrors",
        propositionB : "Check your blind spots",
        propositionC : "Signal your intentions",
        propositionD : "All of the above",
        reponse : "D"},
        
    {   question : "What blood alcohol level is classified as driving while intoxicated?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
        
    {   question : "You must pull over and stop until any emergency vehicle with a siren has passed, unless:",
        propositionA : "You are in a hurry",
        propositionB : "There is enough room for them in a nother lane",
        propositionC : "You are in a school zone",
        propositionD : "You are in an intersection",
        reponse : "D"},
    
    {   question : "Right-of-way must be yielded to emergency vehicles",
        propositionA : "At all times",
        propositionB : "When flashing red, blue, or white lights",
        propositionC : "When using a siren or flashing red, blue, or white lights",
        propositionD : "When using a siren",
        reponse : "C"},
        
    {   question : "Which of the following IS permitted when passing another vehicle?",
        propositionA : "Following closely",
        propositionB : "Leaving the main traveled roadway",
        propositionC : "Driving on the opposite side of the road",
        propositionD : "Exceeding the speed limit",
        reponse : "C"},
        
    {   question : "You are driving on a freeway with a posted speed limit of 70 mph. Most of the traffic is traveling at 80 mph, so you should be driving no faster than",
        propositionA : "80 mph",
        propositionB : "40 mph",
        propositionC : "50 mph",
        propositionD : "70 mph",
        reponse : "D"},
        
    {   question : "When being passed by another vehicle, it is important NOT to",
        propositionA : "Slow down",
        propositionB : "Check your mirrors",
        propositionC : "Look at the other driver",
        propositionD : "Speed up",
        reponse : "D"},
        
    {   question : "Which occupants of a passenger vehicle must wear safety belts?",
        propositionA : "The driver and rear seat passengers",
        propositionB : "Nobody",
        propositionC : "The driver, front-seat passengers",
        propositionD : "All passengers",
        reponse : "D"},
    
    {   question : "What drugs are you allowed to drive on?",
        propositionA : "Any drugs",
        propositionB : "Marijuana",
        propositionC : "None",
        propositionD : "Cocaine",
        reponse : "C"},
    
    {   question : "Where are you allowed to park your vehicle?",
        propositionA : "Anywhere",
        propositionB : "Marked parking spots",
        propositionC : "In the middle of the road",
        propositionD : "Near a fire hydrant",
        reponse : "B"},
    
    {   question : "What does a red light mean?",
        propositionA : "Stop",
        propositionB : "Slow down",
        propositionC : "GO!",
        propositionD : "Slow down and look for an officer, if none found continue through the light",
        reponse : "A"},
    
    {   question : "What makes a vehicle unroadworthy?",
        propositionA : "Broken window",
        propositionB : "Missing door",
        propositionC : "No license plate",
        propositionD : "All of the above",
        reponse : "D"},
    
    {   question : "You may legally block an intersection:?",
        propositionA : "When you entered the intersection on the green light.",
        propositionB : "During rush hour traffic.",
        propositionC : "Never",
        propositionD : "Always",
        reponse : "C"},
    
    {   question : "__________ on your side of the road indicates a no-passing zone.",
        propositionA : "A solid yellow line",
        propositionB : "A broken white line",
        propositionC : "A broken yellow line",
        propositionD : "None of the above",
        reponse : "A"},
    
    {   question : "Areas of the road that you cannot see in your mirrors are called?",
        propositionA : "Invisible spots",
        propositionB : "Blind spots",
        propositionC : "Blank spots",
        propositionD : "Special zones",
        reponse : "B"},
    
    {   question : "What is the speedlimit when driving around a town?",
        propositionA : "25",
        propositionB : "55",
        propositionC : "70",
        propositionD : "40",
        reponse : "D"},
    
    {   question : "If you are driving faster than the other traffic on a freeway, you should use",
        propositionA : "The right lane",
        propositionB : "The shoulder",
        propositionC : "The middle or left lane",
        propositionD : "Any lane",
        reponse : "C"},
  
    {   question : "You may not park your vehicle:",
        propositionA : "On the side of the freeway in an emergency.",
        propositionB : "Next to a red painted curb",
        propositionC : "Next to a white painted curb.",
        propositionD : "In a parking lot.",
        reponse : "B"},
    
    {   question : "What does a RED OCTAGON shaped sign mean",
        propositionA : "Caution ahead",
        propositionB : "Stop",
        propositionC : "Merge left",
        propositionD : "Dip ahead",
        reponse : "B"},
    
    {   question : "When you're driving on the highway, you can prevent highway hypnosis by",
        propositionA : "Shifting your eyes frequently",
        propositionB : "Listening to loud music",
        propositionC : "Taking simulants",
        propositionD : "Talking on your cellphone",
        reponse : "A"},
    
    {   question : "When driving at night you should ",
        propositionA : "Use your lights",
        propositionB : "Drive with caution",
        propositionC : "Focus on the road",
        propositionD : "All of the above",
        reponse : "D"},
    
    {   question : "Name some places where you are likely to find slippery spots on the road.",
        propositionA : "In corners and at stop signs.",
        propositionB : "In shady spots and on overpasses and bridges.",
        propositionC : "In tunnels and on hills.",
        propositionD : "Near large bodies of water.",
        reponse : "B"},
 
    {   question : "When may a driver use a handicapped parking space? ",
        propositionA : "If a physically handicapped person is in the motor vehicle when it is parked.",
        propositionB : "If a physically handicapped person is being delivered or picked up.",
        propositionC : "If the vehicle displays a handicapped person placard or license plates.",
        propositionD : "All of the above.",
        reponse : "C"},
    
    {   question : "When approaching an intersection where there are no signs or traffic lights, you must",
        propositionA : "Yield to vehicles on the left",
        propositionB : "Yield to heavy vehicles",
        propositionC : "Yield to vehicles on the right",
        propositionD : "Slow down and proceed with caution",
        reponse : "C"},
    
    {   question : "If a tire blows out, you should",
        propositionA : "Let go of the gas pedal",
        propositionB : "Hit your brakes hard to avoid a collision",
        propositionC : "Swerve to the side of the road",
        propositionD : "Keep straight and let your vehicle come to a stop on its own",
        reponse : "D"},
    
    {   question : "When driving above 30 mph you should stay _____ seconds behind the vehicle ahead of you.",
        propositionA : "6",
        propositionB : "4",
        propositionC : "10",
        propositionD : "5",
        reponse : "B"},
    
    {   question : "It is unsafe for you to pass when",
        propositionA : "The vehicle ahead is traveling slower than the safe speed",
        propositionB : "The pavement markings are broken yellow lines",
        propositionC : "The pavement markings are broken white lines",
        propositionD : "You are moving through an intersection",
        reponse : "D"},
       
    {   question : "If you want to turn left at an intersection but oncoming traffic is heavy. What should you do?",
        propositionA : "Start your turn forcing others to stop.",
        propositionB : "Wait at the crosswalk for traffic to clear.",
        propositionC : "Wait in the center of the intersection for traffic to clear.",
        propositionD : "All of the above.",
        reponse : "C"},
    
    {   question : "When should you switch on your high-beam headlights?",
        propositionA : "All night",
        propositionB : "When driving in open country or on dark city streets",
        propositionC : "At night when it rains",
        propositionD : "All of the above",
        reponse : "B"},
        
    {   question : "A traffic light changes from green to yellow as you approach an intersection. What do you do?",
        propositionA : "Keep going at your current speed.",
        propositionB : "Stop before the intersection.",
        propositionC : "Stop, even if in the intersection.",
        propositionD : "Speed up to beat the light before it turns red.",
        reponse : "B"},
    
    {   question : "_________ are the most likely places for car and motorcycle collisions to occur.",
        propositionA : "Expressway",
        propositionB : "Roundabouts",
        propositionC : "One way roads",
        propositionD : "Intersections",
        reponse : "D"},
    
    {   question : "What should you do if you are overtaking a bicycle and an oncoming vehicle is approaching at the same time?",
        propositionA : "Leave little room for the oncoming vehicle while overtaking the bicycle",
        propositionB : "Sound your horn to alert the bicyclist",
        propositionC : "Slow down and let the oncoming vehicle pass first to leave extra room for the bicycle",
        propositionD : "Overpass the bicycle first to leave extra room for the oncoming traffic",
        reponse : "C"},
    
    {   question : "What is a speedlimit?",
        propositionA : "Recommended safe speed",
        propositionB : "The minimum speed you can travel",
        propositionC : "Speedlimits mean nothing",
        propositionD : "The maximum speed you can travel",
        reponse : "D"},
    
    {   question : "Lanes of traffic going in opposite directions are divided by",
        propositionA : "Yellow lines",
        propositionB : "White line",
        propositionC : "Black lines",
        propositionD : "Red lines",
        reponse : "A"},
    
    {   question : "What should you do if another driver tailgates your vehicle?",
        propositionA : "Flick the driver off and tell him to fuck off",
        propositionB : "Keep driving slow in front of the tailgater",
        propositionC : "Pull over and allow the driver to pass",
        propositionD : "Increase your speed",
        reponse : "C"},
    
    {   question : "What is the illegal window tint amount?",
        propositionA : "Pure Black",
        propositionB : "Dark Smoke",
        propositionC : "Light Smoke",
        propositionD : "Green",
        reponse : "A"},
    
    {   question : "What is considered Reckless Driving?",
        propositionA : "Speeding 30mph over the speed limit",
        propositionB : "Driving in the wrong lane of traffic",
        propositionC : "Running multiple red lights",
        propositionD : "All of the above",
        reponse : "D"},
    
    {   question : "What are you allowed to do without a valid drivers license?",
        propositionA : "Rent a rental vehicle",
        propositionB : "Rent a bicycle",
        propositionC : "Drive around in your vehicle",
        propositionD : "Purchase a vehicle",
        reponse : "B"},
]
