resource_manifest_version '05cfa83c-a124-4cfa-a768-c24a5811d8f9'

client_scripts {
	"Utilities/Shared/Config.lua",
	"Wrappers/Shared/Log.lua",
	"Wrappers/Shared/Chat.lua",
	"Utilities/Shared/Functions.lua",
	"Wrappers/Client/Decorator.lua",
	"Wrappers/Client/Animation.lua",
	"Wrappers/Client/Map.lua",
	"Wrappers/Client/Blip.lua",
	"Utilities/Client/Functions.lua",
	"Utilities/Client/Drawing.lua",
	"Wrappers/Client/NativeUI.lua",
	"Player/Client/Main.lua",
	"Player/Client/Death.lua",
	"Player/Client/Emotes.lua",
	"Player/Client/Stance.lua",
	"Player/Client/Surrender.lua",
	"Player/Client/Drunk.lua",
	"Player/Client/Deer Riding.lua",
	"Player/Client/Seatbelt.lua",
	"Player/Client/Commands.lua",
	"Vehicles/Client/Garages.lua",
	"Vehicles/Client/Shop.lua",
	"Police/Client/Cuffing.lua",
	"Police/Client/Spikes.lua",
	"Police/Client/Portable Radar.lua",
	"Police/Client/Shield.lua",
	"weapons.lua",
}

server_scripts {
	"Utilities/Shared/Config.lua",
	"Wrappers/Shared/Log.lua",
	"Wrappers/Shared/Chat.lua",
	"Utilities/Shared/Functions.lua",
	"Utilities/Server/Functions.lua",
	"Player/Server/Death.lua",
	"Vehicles/Server/Garages.lua",
	"Vehicles/Server/Shop.lua",
	"Police/Server/Cuffing.lua",
	"Police/Server/Spikes.lua",
}