Citizen.CreateThread(function()
	AddTextEntryByHash(0x004D4C50, "NISSAN")
	AddTextEntryByHash(0x5D1DDD67, "Paintable")
	AddTextEntryByHash(0x6D787E1C, "Paintable")
	AddTextEntryByHash(0x7EE320F1, "Paintable")
	AddTextEntryByHash(0xA722CA58, "GT-R NISMO")
	AddTextEntryByHash(0xACF5D972, "GT3 Hood")

	AddTextEntry("police_wing_1", "Spoiler A")
	AddTextEntry("police_wing_2", "Spoiler B")
	AddTextEntry("police_wing_3", "Spoiler C")
	AddTextEntry("police_wing_4", "Spoiler D")
	AddTextEntry("police_wing_5", "Spoiler E")
	AddTextEntry("police_wing_6", "Spoiler F")
	AddTextEntry("police_wing_7", "Spoiler G")
	AddTextEntry("police_cage", "Rollcage")
	AddTextEntry("police_cage_2", "Rollcage & RaceSeats")
	AddTextEntry("police_exh1", "Custom Exhaust")
	AddTextEntry("police_roof", "Roof Spoiler")
end)