vehicleList = {
    ["normal"] = {
        {
            title = "Job Vehicles", 
            vehicles = {
                {name = "Taxi", model = "taxi"},
                {name = "Taco Truck", model = "taco"},
                {name = "Tour Bus", model = "tourbus"},
            }
        },
        {
            title = "Compacts", 
            vehicles = {
                {name = "Blista", model = "blista"},
                {name = "Brioso R/A", model = "brioso"},
                {name = "Dilettante", model = "dilettante"},
                {name = "Issi", model = "issi2"},
                {name = "Panto", model = "panto"},
                {name = "Prairie", model = "prairie"},
                {name = "Rhapsody", model = "rhapsody"},
                {name = "Issi Classic", model = "issi3"},
                {name = "Blista Kanjo", model = "kanjo"},
                {name = "Asbo", model = "asbo"},
            }
        },
        {
            title = "Coupes", 
            vehicles = {
                {name = "Exemplar", model = "exemplar"},
                {name = "F620", model = "f620"},
                {name = "Felon", model = "felon"},
                {name = "Felon GT", model = "felon2"},
                {name = "Jackal", model = "jackal"},
                {name = "Oracle", model = "oracle"},
                {name = "Oracle XS", model = "oracle2"},
                {name = "Sentinel XS", model = "sentinel"},
                {name = "Sentinel", model = "sentinel2"},
                {name = "Zion", model = "zion"},
                {name = "Zion Cabrio", model = "zion2"},
            }
        },
        {
            title = "Sports", 
            vehicles = {
                {name = "Alpha", model = "alpha"},
                {name = "Banshee", model = "banshee"},
                {name = "Bestia GTS", model = "bestiagts"},
                {name = "Buffalo", model = "buffalo"},
                {name = "Buffalo S", model = "buffalo2"},
                {name = "Coil Raiden", model = "raiden"},
                {name = "Comet Retro Custom", model = "comet3"},
                {name = "Comet Safari", model = "comet4"},
                {name = "Drift Tampa", model = "tampa2"},
                --{name = "Hotring Sabre", price = 42500, model = "hotring"}, -- Assault Pack
                {name = "Elegy RH8", model = "elegy2"},
                {name = "Elegy Retro Custom", model = "elegy"},
                {name = "Feltzer", model = "feltzer2"},
                {name = "Furore GT", model = "furoregt"},
                {name = "Fusilade", model = "fusilade"},
                {name = "Futo", model = "futo"},
                {name = "Go Go Monkey Blista", model = "blista3"},
                {name = "Jester", model = "jester"},
                {name = "Jester Race", model = "jester2"},
                {name = "Khamelion", model = "khamelion"},
                {name = "Kuruma", model = "kuruma"},
                --{name = "Kuruma Armored", price = 333000, model = "kuruma2"}, -- Armoured car
                {name = "Lynx", model = "lynx"},
                {name = "Massacro", model = "massacro"},
                {name = "Massacro Race", model = "massacro2"},
                {name = "Neon", model = "neon"},
                {name = "Omnis", model = "omnis"},
                {name = "Pariah", model = "pariah"},
                {name = "Penumbra", model = "penumbra"},
                {name = "Rapid GT", model = "rapidgt"},
                {name = "Rapid GT Convertible", model = "rapidgt2"},
                {name = "Raptor", model = "raptor"},
                {name = "Revolter", model = "revolter"},
                {name = "Ruston", model = "ruston"},
                {name = "Schafter LWB", model = "schafter4"},
                {name = "Schwarzer", model = "schwarzer"},
                {name = "Sentinel Classic", model = "sentinel3"},
                {name = "Sprunk Buffalo", model = "buffalo3"},
                {name = "Streiter", model = "streiter"},
                {name = "Sultan", model = "sultan"},
                {name = "Sultan RS", model = "sultanrs"},
                {name = "Surano", model = "surano"},
                {name = "Tropos Rallye", model = "tropos"},
                {name = "Verlierer", model = "verlierer2"},
                {name = "Blista Compact", model = "blista2"},
                {name = "8F Drafter", model = "drafter"},
                {name = "GB200", model = "gb200"},
                {name = "Issi Sport", model = "issi7"},
                {name = "Komoda", model = "komoda"},
                {name = "Locust", model = "locust"},
                {name = "Sugoi", model = "sugoi"},
                {name = "Sultan Classic", model = "sultan2"},
                {name = "Neo", model = "neo"},
            }
        },
        {
            title = "Sports Classics", 
            vehicles = {
                {name = "Ardent", model = "ardent"},
                {name = "Casco", model = "casco"},
                {name = "Fränken Strange", model = "btype2"},
                {name = "GT 500", model = "gt500"},
                {name = "Jester Classic", model = "jester3"},
                {name = "JB 700", model = "jb700"},
                {name = "Karin 190z", model = "z190"},
                {name = "Manana", model = "manana"},
                {name = "Monroe",  model = "monroe"},
                {name = "Peyote", model = "peyote"},
                {name = "Pigalle", model = "pigalle"},
                {name = "Retinue", model = "retinue"},
                {name = "Roosevelt", model = "btype"},
                {name = "Roosevelt Valor", model = "btype3"},
                -- {name = "Savestra", model = "savestra"},
                {name = "Stinger GT", model = "stingergt"},
                {name = "Torero", model = "torero"},
                {name = "Tornado", model = "tornado"},
                {name = "Tornado (Beater)", model = "tornado3"},
                {name = "Tornado (Mariachi)", model = "tornado4"},
                {name = "Tornado Custom", model = "tornado5"},
                {name = "Tornado Rat Rod", model = "tornado6"},
                {name = "Turismo Classic", model = "turismo2"},
                {name = "Viseris", model = "viseris"},
                {name = "Z-type", model = "ztype"},
                {name = "Dynasty", model = "dynasty"},
                {name = "Fagaloa", model = "fagaloa"},
                {name = "Cheburek", model = "cheburek"},
                {name = "Michelli GT", model = "michelli"},
                {name = "Nebula Turbo", model = "nebula"},
                {name = "Retinue MK2", model = "retinue2"},
                --{name = "Stromberg", model = "stromberg"}, -- Submarine and Guns
            }
        },
        {
            title = "Muscle", 
            vehicles = {
                {name = "Blade", model = "blade"},
                {name = "Buccaneer", model = "buccaneer"},
                {name = "Buccaneer Custom", model = "buccaneer2"},
                --{name = "Burger Shot Stallion", price = 0, model = "stallion2"}, -- Doesnt load in the shop?
                {name = "Chino", model = "chino"},
                {name = "Chino Custom", model = "chino2"},
                {name = "Coquette BlackFin", model = "coquette3"},
                {name = "Dominator", model = "dominator"},
                {name = "Dominator GTX", model = "dominator3"}, -- Assault Pack
                {name = "Dukes", model = "dukes"},
                --{name = "Duke O'Death", price = 0, model = "dukes2"}, -- Armoured car
                {name = "Gauntlet", model = "gauntlet"},
                {name = "Hermes", model = "hermes"},
                {name = "Hotknife", model = "hotknife"},
                {name = "Hustler",  model = "hustler"},
                {name = "Faction", model = "faction"},
                {name = "Faction Custom", model = "faction2"},
                {name = "Faction Custom Donk", model = "faction3"},
                {name = "Lost Slamvan", model = "slamvan2"},
                {name = "Lurcher", model = "lurcher"},
                {name = "Moonbeam", model = "moonbeam"},
                {name = "Moonbeam Custom", model = "moonbeam2"},
                {name = "Nightshade", model = "nightshade"},
                {name = "Phoenix", model = "phoenix"},
                {name = "Picador", model = "picador"},
                {name = "Pißwasser Dominator", model = "dominator2"},
                {name = "Rat-Loader", model = "ratloader"},
                {name = "Rat-Truck", model = "ratloader2"},
                {name = "Redwood Gauntlet", model = "gauntlet2"},
                {name = "Ruiner", model = "ruiner"},
                --{name = "Ruiner 2000", price = 0, model = "ruiner2"}, --This vehicle has guns, parachute, rockets etc
                {name = "Sabre Turbo", model = "sabregt"},
                {name = "Sabre Turbo Custom", model = "sabregt2"},
                {name = "Slamvan", model = "slamvan"},
                {name = "Slamvan Custom", model = "slamvan3"},
                --{name = "Stallion", price = 0, model = "stallion"}, --Doesnt load in the shop?
                {name = "Tampa", model = "tampa"},
                {name = "Virgo", model = "virgo"},
                {name = "Virgo Classic", model = "virgo2"},
                {name = "Virgo Classic Custom", model = "virgo3"},
                {name = "Vigero", model = "vigero"},
                {name = "Voodoo", model = "voodoo2"},
                {name = "Voodoo Custom", model = "voodoo"},
                {name = "Deviant", model = "deviant"},
                {name = "Drift Yosemite", model = "yosemite2"},
                {name = "Ellie", model = "ellie"},
                {name = "Gauntlet Classic", model = "gauntlet3"},
                {name = "Gauntlet Hellfire", model = "gauntlet4"},
                {name = "Impaler", model = "impaler"},
                {name = "Stallion", model = "stalion"},
                {name = "Tulip", model = "tulip"},
                {name = "Clique", model = "clique"},
                {name = "Vamos", model = "vamos"},
            }
        },
        {
            title = "Offroad", 
            vehicles = {
                {name = "Bifta", model = "bifta"},
                {name = "Bodhi", model = "bodhi2"},
                {name = "Brawler", model = "brawler"},
                {name = "Canis Kamacho", model = "kamacho"},
                {name = "Desert Raid", model = "trophytruck2"},
                {name = "Dubsta 6x6", model = "dubsta3"},
                {name = "Dune Buggy", model = "dune"},
                {name = "Duneloader", model = "dloader"},
                {name = "Injection", model = "bfinjection"},
                {name = "Kalahari", model = "kalahari"},
                {name = "Mesa (Caged)", model = "mesa3"},
                --{name = "Nightshark", price = 0, model = "nightshark"}, -- Armoured car
                {name = "Riata", model = "riata"},
                {name = "Rebel", model = "rebel2"},
                {name = "Rusty Rebel", model = "rebel"},
                {name = "Trophy Truck", model = "trophytruck"},
                {name = "Hot Rod Blazer", model = "blazer3"},
                {name = "Street Blazer", model = "blazer4"},
                {name = "Caracara 4x4", model = "caracara2"},
                {name = "Everon", model = "everon"},
                {name = "Freecrawler", model = "freecrawler"},
                {name = "Hellion", model = "hellion"},
                {name = "Outlaw", model = "outlaw"},
                {name = "Vagrant", model = "vagrant"},
            }
        }, 
        {
            title = "SUV", 
            vehicles = {
                {name = "Baller", model = "baller"},
                {name = "Baller 2nd Gen", model = "baller2"},
                {name = "Baller LE", model = "baller3"},
                {name = "Baller LE LWB", model = "baller4"},
                {name = "BeeJay XL", model = "bjxl"},
                {name = "Cavalcade", model = "cavalcade"},
                {name = "Cavalcade 2nd Gen",model = "cavalcade2"},
                {name = "Dubsta", model = "dubsta2"},
                {name = "FQ 2", model = "fq2"},
                {name = "Granger", model = "granger"},
                {name = "Gresley", model = "gresley"},
                {name = "Habanero", model = "habanero"},
                {name = "Huntley S", model = "huntley"},
                {name = "Landstalker", model = "landstalker"},
                {name = "Mesa", model = "mesa"},
                {name = "Patriot", model = "patriot"},
                {name = "Radius", model = "radi"},
                {name = "Rocoto", model = "rocoto"},
                {name = "Seminole", model = "seminole"},
                {name = "Serrano", model = "serrano"},
                {name = "Dubsta 2nd Gen", model = "dubsta"},
                {name = "Novak", model = "novak"},
                {name = "Patriot Stretch", model = "patriot2"},
                {name = "Rebla GTS", model = "rebla"},
                {name = "XLS", model = "xls"},
            }
        }, 
        {
            title = "Vans", 
            vehicles = {
                {name = "Burrito", model = "burrito3"},
                {name = "Camper", model = "camper"},
                {name = "Gang Burrito", model = "gburrito2"},
                {name = "Journey", model = "journey"},
                {name = "Minivan", model = "minivan"},
                {name = "Minivan Custom", model = "minivan2"},
                {name = "Paradise", model = "paradise"},
                {name = "Rumpo", model = "rumpo"},
                {name = "Rumpo Custom", model = "rumpo3"},
                {name = "Surfer", model = "surfer"},
                {name = "Surfer (Beater)", model = "surfer2"},
                {name = "Youga", model = "youga"},
                {name = "Youga Classic", model = "youga2"},
                {name = "Speedo", model = "speedo"},
                {name = "Pony", model = "pony2"},
            }
        },
        {
            title = "Trucks", 
            vehicles = {
                {name = "Sadler", model = "sadler"},
                {name = "Bison", model = "bison"},
                {name = "Bobcat XL", model = "bobcatxl"},
                {name = "Contender", model = "contender"},
                {name = "Rancher XL", model = "rancherxl"},
                {name = "Sandking SWB", model = "sandking2"},
                {name = "Sandking XL", model = "sandking"},
            }
        },
        {
            title = "Sedans", 
            vehicles = {
                {name = "Asea", model = "asea"},
                {name = "Asterope", model = "asterope"},
                {name = "Emperor", model = "emperor"},
                {name = "Emperor (Beater)", model = "emperor2"},
                {name = "Fugitive", model = "fugitive"},
                {name = "Glendale", model = "glendale"},
                {name = "Ingot", model = "ingot"},
                {name = "Intruder", model = "intruder"},
                {name = "Premier", model = "premier"},
                {name = "Primo", model = "primo"},
                {name = "Primo Custom", model = "primo2"},
                {name = "Regina", model = "regina"},
                {name = "Romero Hearse", model = "romero"},
                {name = "Schafter", model = "schafter2"},
                {name = "Stanier", model = "stanier"},
                {name = "Stratum", model = "stratum"},
                {name = "Stretch Limo", model = "stretch"},
                {name = "Surge", model = "surge"},
                {name = "Tailgater", model = "tailgater"},
                {name = "Warrener", model = "warrener"},
                {name = "Washington", model = "washington"},
            }
        }, 
        {
            title = "Motorcycles", 
            vehicles = {
                {name = "Akuma", model = "akuma"},
                {name = "Avarus", model = "avarus"},
                {name = "Bagger", model = "bagger"},
                {name = "Bati 801", model = "bati"},
                {name = "Bati 801RR",model = "bati2"},
                {name = "BF400", model = "bf400"},
                {name = "Carbon RS", model = "carbonrs"},
                {name = "Cliffhanger", model = "cliffhanger"},
                {name = "Daemon", model = "daemon2"},
                {name = "Daemon (Lost)", model = "daemon"},
                {name = "Defiler", model = "defiler"},
                {name = "Diablous", model = "diablous"},
                {name = "Diablous Custom", model = "diablous2"},
                {name = "Double T", model = "double"},
                {name = "Enduro", model = "enduro"},
                {name = "Esskey", model = "esskey"},
                {name = "Faggio", model = "faggio2"},
                {name = "Faggio Sport",model = "faggio"},
                {name = "Faggio Mod", model = "faggio3"},
                {name = "FCR 1000", model= "fcr"},
                {name = "FCR 1000 Custom", model = "fcr2"},
                {name = "Gargoyle", model = "gargoyle"},
                {name = "Hakuchou", model = "hakuchou"},
                {name = "Hakuchou Drag", model = "hakuchou2"},
                {name = "Hexer", model = "hexer"},
                {name = "Innovation", model = "innovation"},
                {name = "Lectro", model = "lectro"},
                {name = "Manchez", model = "manchez"},
                {name = "Nemesis", model = "nemesis"},
                {name = "Nightblade", model = "nightblade"},
                {name = "PCJ-600", model = "pcj"},
                {name = "Rat Bike", model = "ratbike"},
                {name = "Ruffian", model = "ruffian"},
                {name = "Sanchez", model = "sanchez"},
                {name = "Sanctus", model = "Sanctus"},
                {name = "Sovereign", model = "sovereign"},
                {name = "Thrust", model = "thrust"},
                {name = "Vader", model = "vader"},
                {name = "Vindicator", model = "vindicator"},
                {name = "Vortex", model = "vortex"},
                {name = "Wolfsbane", model = "wolfsbane"},
                {name = "Zombie Bobber", model = "zombiea"},
                {name = "Zombie Chopper", model = "zombieb"},
                {name = "Rampant Rocket", model = "rrocket"},
            }
        },
    },
    ["luxury"] = {
	
        {
            title = "Sports", 
            vehicles = {
                {name = "9F", model = "ninef"},
                {name = "9F Cabrio", model = "ninef2"},
                {name = "Banshee 900R", model = "banshee2"},
                {name = "Carbonizzare", model = "carbonizzare"},
                {name = "Comet", model = "comet2"},
                {name = "Comet SR", model = "comet5"},
                {name = "Coquette", model = "coquette"},
                {name = "Jester", model = "jester"},
                {name = "Jester Race", model = "jester2"},
                {name = "Schafter V12", model = "schafter3"},
                {name = "Seven-70", model = "seven70"},
                {name = "Specter", model = "specter"},
                {name = "Specter Custom", model = "specter2"},
                {name = "Imorgon", model = "imorgon"},
                {name = "Itali GTO", model = "italigto"},
                {name = "Jugular", model = "jugular"},
                {name = "Paragon", model = "paragon"},
                {name = "Schlagen GT", model = "schlagen"},
                {name = "V-STR", model = "vstr"},
            }
        },
        {
            title = "Sports Classics", 
            vehicles = {
                {name = "Cheetah Classic", model = "cheetah2"},
                {name = "Coquette Classic", model = "coquette2"},
                {name = "Infernus Classic", model = "infernus2"},
                {name = "Mamba", model = "mamba"},
                {name = "Rapid GT Classic", model = "rapidgt3"},
                {name = "Stinger", model = "stinger"},
                {name = "Stirling GT", model = "feltzer3"},
                {name = "Swinger", model = "swinger"},
                {name = "Stinger GT", model = "stingergt"},
                {name = "Turismo Classic", model = "turismo2"},
            }
        },
        {
            title = "Super", 
            vehicles = {
                {name = "Adder", model = "adder"},
                {name = "Autarch", model = "autarch"},
                {name = "Bullet", model = "bullet"},
                {name = "Cheetah", model = "cheetah"},
                {name = "Cyclone", model = "cyclone"},
                {name = "Deveste Eight", model = "deveste"},
                {name = "811", model = "pfister811"},
                {name = "Emerus", model = "emerus"},
                {name = "Entity XF", model = "entityxf"},
                {name = "Entity XXR", model = "entity2"},
                {name = "FMJ", model = "fmj"},
                {name = "Furia", model = "furia"},
                {name = "GP1", model = "gp1"},
                {name = "Infernus", model = "infernus"},
                {name = "Itali GTB", model = "italigtb"},
                {name = "Itali GTB Custom", model = "italigtb2"},
                {name = "Kreiger", model = "krieger"},
                {name = "Nero", model = "nero"},
                {name = "Nero Custom", model = "nero2"},
                {name = "Osiris", model = "osiris"},
                {name = "Penetrator", model = "penetrator"},
                {name = "Reaper", model = "reaper"},
                {name = "SC1", model = "sc1"},
                {name = "T20", model = "t20"},
                {name = "Taipan", model = "taipan"},
                {name = "Tempestra", model = "tempesta"},
                {name = "Tezeract", model = "tezeract"},
                {name = "Thrax", model = "thrax"},
                {name = "Turismo R", model = "turismor"},
                {name = "Tyrant", model = "tyrant"},
                {name = "Vacca", model = "vacca"},
                {name = "Vagner", model = "vagner"},
                {name = "Visione", model = "visione"},
                {name = "Voltic", model = "voltic"},
                {name = "XA-21", model = "xa21"},
                {name = "X80 Proto", model = "prototipo"},
                {name = "Zentorno", model = "zentorno"},
                {name = "Zorrusso", model = "zorrusso"},
            }
        },
        {
            title = "Sedans", 
            vehicles = {
                {name = "Cognoscenti", model = "cog55"},
                {name = "Cognoscenti 55", model = "cognoscenti"},
                {name = "Super Diamond", model = "superd"},
            }
        },
        {
            title = "SUV", 
            vehicles = {
                {name = "Toros", model = "toros"},
            }
        },
        {
            title = "Coupes", 
            vehicles = {
                {name = "Cognoscenti Cabrio", model = "cogcabrio"},
                {name = "Windsor", model = "windsor"},
                {name = "Windsor Drop", model = "windsor2"},
            }
        },
    },
    ["import"] = {

    },
}